// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF20pDcMtgCc9HuHEj5hdWPRpQQTa7fos',
    appId: '1:883959527648:web:fac288903219ec7304b885',
    messagingSenderId: '883959527648',
    projectId: 'period-ik',
    authDomain: 'period-ik.firebaseapp.com',
    storageBucket: 'period-ik.firebasestorage.app',
    measurementId: 'G-7PDX0Y20YT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBX-Z87gjH16je18cqr3Tsv3f9wPCug_U',
    appId: '1:883959527648:android:c51ab160cdce291804b885',
    messagingSenderId: '883959527648',
    projectId: 'period-ik',
    storageBucket: 'period-ik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD98CbtdYITZL9qPUPX0X7VAWV2yz_n-9w',
    appId: '1:883959527648:ios:147e83497cdeeae004b885',
    messagingSenderId: '883959527648',
    projectId: 'period-ik',
    storageBucket: 'period-ik.firebasestorage.app',
    androidClientId:
        '883959527648-5astk55m3pnfc735c2jtehq3j1kjce7d.apps.googleusercontent.com',
    iosClientId:
        '883959527648-bd3vth4qi80j0jdtgt6f1naggnb0db8i.apps.googleusercontent.com',
    iosBundleId: 'com.valentinvignal.periodik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD98CbtdYITZL9qPUPX0X7VAWV2yz_n-9w',
    appId: '1:883959527648:ios:147e83497cdeeae004b885',
    messagingSenderId: '883959527648',
    projectId: 'period-ik',
    storageBucket: 'period-ik.firebasestorage.app',
    androidClientId:
        '883959527648-5astk55m3pnfc735c2jtehq3j1kjce7d.apps.googleusercontent.com',
    iosClientId:
        '883959527648-bd3vth4qi80j0jdtgt6f1naggnb0db8i.apps.googleusercontent.com',
    iosBundleId: 'com.valentinvignal.periodik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwyT9jH5N0zOInVjiYX1SgEl-6is8EWo0',
    appId: '1:883959527648:web:5fa373b071d67ae704b885',
    messagingSenderId: '883959527648',
    projectId: 'period-ik',
    authDomain: 'period-ik.firebaseapp.com',
    storageBucket: 'period-ik.firebasestorage.app',
    measurementId: 'G-XQJ3SXNRTY',
  );
}
